### ISSUE TITLE
Show other players death locations in chat

### ISSUE THREAD

**Issue by derp90** [ChazMeister/DeathLocation#1]
Is it possible to show other players death locations in the chat as well?

**Comment by ChazMeister** [comment]
Hello, thanks for the suggestion.

I'm not sure if that can be done without a mod running on the server and I kind of want to keep this really simple and just client side for now.

May work on that in the future, but not right now.

**Comment by derp90** [comment]
Ahh thank you thank makes so much sense, would it be possible as an option to put your death location into the chat instead?

**Comment by ChazMeister** [comment]
Hmm, I'm not a big fan of an automatic coordinate broadcast message.

I could add clicking on the death coordinates copies them to the clipboard and then that can be pasted into a message or a teleport command or something quickly.

I'll implement that soon.

Thanks!

**Comment by ChazMeister** [comment]
Hello,

In 6d33a7e I added the feature described in my last comment.

Hopefully that works for you, I've uploaded v1.1 to Modrinth which contains this change.
