### ISSUE TITLE
[Bug] Coordinates message not sent while doImmediateRespawn is on

### ISSUE THREAD

**Issue by ghost** [ChazMeister/DeathLocation#2]
<h2>[Bug] Coordinates message not sent while doImmediateRespawn is on</h2>
Disclaimer: I am unsure if this is an intentional feature or not. 
After turning on the gamerule doImmediateRespawn, the death coordinates do not appear. Turning the gamerule off causes the death coordinates to be sent to the player again. 

I do not believe this is a mod compatibility issue, and thus have not provided a mod list. I will provide one if necessary.

Screenshot for reference:
 
![image](https://github.com/ChazMeister/DeathLocation/assets/157556010/7e903d82-343d-4b3b-a6a9-8aee895ea0bd)

The death message appears consistently after the gamerule is set to false.

**Comment by ChazMeister** [comment]
Hello, thank you for the report.

That makes sense, I wasn't aware of the doImmediateRespawn gamerule so the message is triggered by the death screen at the moment.

I'll look into solving this.

**Comment by ChazMeister** [comment]
Hello,

Fixed in 6d33a7e.

I've uploaded v1.1 to Modrinth, that should solve this issue!

**Comment by ghost** [comment]
Thanks, the fix works great!
